Cbs v2
Simson475/Swarm-Robotics pull request #12
Opened 2022-04-01 12:55 UTC by Suprezer

Removed subtype and error logs

2022-04-02 19:40 UTC, BjoerklundJacob requested changes

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/Pathfinding/ActionPathAux.cpp
> +    return a.priority <= b.priority;
fair nok at lave den extra så det passer med comparison, men så skal den da ikke være >=, men kun >

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    Action firstAction = agent->getBot()->getCurrentAction();
Det her kan vi ikke. Eller måske bare et problem ved merge i hvert fald. For vi må ikke have access til controllers fra vores pathfinding for at vi kan teste. 
Så current action bør ligge på agent og ikke controller (Eller i hvert fald som minimum være en property der henter den på agent, så når vi kalder agent->getAgentInfo får den hevet med)

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    //std::priority_queue<ActionPathAux, std::vector<ActionPathAux>, std::smaller<ActionPathAux>> priorityQueue{};
Skal bare slettes, ingen grund til at have den som kommentar :)

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    //actions.push_back(Action(currentTime, vertex, vertex, minWaitTime));
Tænker den her skal med igen ;)

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/controllers/RobotInterface/RobotInterface.cpp
> +
Er det her virkelig nødvendigt?

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/controllers/RobotInterface/RobotInterface.hpp
> +
Bliver ikke brugt

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/controllers/RobotInterface/RobotInterface.hpp
> +    std::string subtype = "default";
Er den her virkelig nødvendig? Synes der mangler en kommentar i forhold til hvorfor det er nødvendigt med det early return ud fra CBS type

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/controllers/TestController.cpp
> +
Igen nødvendigt? Hvis ja, fyr en kommentar om hvorfor

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/controllers/TestController.hpp
> +    void specialInit() override;
Hvis det der type ikke er nødvendigt skal den her fjernes

2022-04-02 19:40 UTC, BjoerklundJacob commented on Simulation/models/jobs/PredefinedDescreteJobGenerator.cpp
> +    for(unsigned long i = 1; i < numOfStations - endStations.size(); i++){
Hvorfor var det igen der var en fejl ved det her?

2022-04-05 06:48 UTC, Simson475 commented on Simulation/Pathfinding/ActionPathAux.cpp
> +    return a.priority <= b.priority;
```suggestion
    return a.priority < b.priority;
```

2022-04-05 06:49 UTC, Simson475 commented on Simulation/Pathfinding/ActionPathAux.cpp
> +    return a.priority >= b.priority;
```suggestion
    return a.priority > b.priority;
```

2022-04-05 06:51 UTC, Simson475 commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    //std::priority_queue<ActionPathAux, std::vector<ActionPathAux>, std::smaller<ActionPathAux>> priorityQueue{};
```suggestion

```

2022-04-05 06:52 UTC, Simson475 commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    //actions.push_back(Action(currentTime, vertex, vertex, minWaitTime));
```suggestion
    actions.push_back(Action(currentTime, vertex, vertex, minWaitTime));
```

2022-04-05 07:04 UTC, BjoerklundJacob commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    Action firstAction = agent->getBot()->getCurrentAction();
Kan ikke rigtigt løses før den anden branch er merged

2022-04-05 07:06 UTC, Zzeeker approved these changes

2022-04-05 09:51 UTC, merged