Bug fixes and experiment
Simson475/Swarm-Robotics pull request #18
Opened 2022-04-29 08:28 UTC by BjoerklundJacob

2022-04-29 08:29 UTC, Zzeeker approved these changes, later dismissed
Boom

2022-05-04 11:47 UTC, Simson475 commented on Simulation/Pathfinding/ActionPathAux.cpp
> +    std::shared_ptr<ActionPathAux> predecessor = this->predecessor;
skriv om. vi har snakket om det :)

2022-05-04 11:49 UTC, Simson475 commented on Simulation/Pathfinding/Experiments/CMakeLists.txt
> +add_definitions(-Wall -O3 -g)# -Werror
fjern -g

2022-05-04 12:01 UTC, Suprezer approved these changes

2022-05-04 12:19 UTC, Simson475 commented on Simulation/Pathfinding/HighLevelCBS.hpp
> +//#include "argos_wrapper/argos_wrapper.hpp"
```suggestion
```

2022-05-04 12:51 UTC, Simson475 requested changes

2022-05-04 12:51 UTC, Simson475 commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    Action workAction = Action(-1, u, u, -1);
fix

2022-05-04 12:51 UTC, Simson475 commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +            // If this action can be a final action (after working) return the path immediately
yeet

2022-05-04 12:51 UTC, Simson475 commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +    float pathEndTime = 0;
rename

2022-05-04 12:53 UTC, Zzeeker commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +        pathEndTime = std::max(c.timeEnd, pathEndTime);
LastConstraintEndTime?

2022-05-04 13:13 UTC, Zzeeker commented on Simulation/Pathfinding/LowLevelCBS.cpp
> +                minWaitTime = std::min(minWaitTime, constraint.timeEnd - currentTime + DELTA);
Possibly constraint.timeStart, though shouldnt change much

2022-05-06 07:42 UTC, Simson475 approved these changes

2022-05-06 10:49 UTC, merged