Prep for exam
Simson475/Swarm-Robotics pull request #25
Opened 2022-05-13 12:04 UTC by BjoerklundJacob

2022-05-17 08:38 UTC, Simson475 commented on Simulation/Pathfinding/Action.cpp
> +        this->duration = std::max(0.0f, this->duration - desyncOffset);
FIX BJØRKLUND

2022-05-17 09:00 UTC, Simson475 commented on Simulation/Pathfinding/Solution.cpp
> +                path.cost = a.timestamp;
skal lige sikre os det her er rigtigt

2022-05-17 09:02 UTC, Simson475 commented on Simulation/Pathfinding/Solution.cpp
> +        if (path.actions.size() > 0){ // If == 0, it means the work action is the current action
```suggestion
        if (!path.actions.empty()){
```

2022-05-17 09:39 UTC, Simson475 requested changes
sync funktionen på action skal skrives om så det er rigtigt :)

2022-05-18 07:22 UTC, BjoerklundJacob commented on Simulation/Pathfinding/Action.cpp
> +        this->duration = std::max(0.0f, this->duration - desyncOffset);
Har du gjort på næste branch :)

2022-05-24 09:16 UTC, closed without merging