CBS-v2
Simson475/Swarm-Robotics pull request #6
Opened 2022-03-29 06:36 UTC by BjoerklundJacob

Refactored the CBS to use more dependency injection.

2022-03-29 09:14 UTC, Zzeeker requested changes

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/Pathfinding/ExperimentData.cpp
> +        if (agent->getId() == 6){
This is a debugging section

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/Pathfinding/ExperimentData.cpp
> +    int i = 0;
Name this ID for clarity

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/Pathfinding/ConstraintTree/Test.hpp
> +class TesterClass{
Actually unused

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/Pathfinding/Agent.cpp
> +    return (vertex->getId() == this->bot->getStationPlan().front()) ? 10 : 1;//TODO actual times!
Probably pretty important for conflicts later

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/Pathfinding/Interfaces/Graph.cpp
> +#define ROBOT_SPEED (0.1)
Hardcoding this seems risky, can we get it from experiment data somehow?

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/Pathfinding/Solution.cpp
> +#include "Solution.hpp"
This is cursed

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/experiment/cbsMap/trajectory.argos
> -<?xml version="1.0" ?>
Makes sure this is added again

2022-03-29 09:14 UTC, Zzeeker commented on Simulation/controllers/TestController.cpp
> +void TestController::updateCurrentLocation(Action action){
Skriv en comment

2022-03-29 09:34 UTC, Zzeeker approved these changes

2022-03-29 10:24 UTC, Simson475 requested changes

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/Action.cpp
> +Action::Action(const Action& a){
kan det gøres pænere?

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/ActionPathAux.cpp
> +#include "ActionPathAux.hpp"
kan vi få et bedre navn?

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/ActionPathAux.cpp
> +    return a.priority > b.priority;
er det her rigtigt?

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/Agent.cpp
> +std::shared_ptr<Vertex> Agent::getGoal(){
kan vi kalde den getStation?

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/Debugging.hpp
> +class Error {
alt gør ondt.

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/ExperimentData.cpp
> +            Error::log(std::to_string(agent->getId()));
remove?

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/HighLevelCBS.cpp
> +            Error::log(">");
kan vi yeete de her error::log?

2022-03-29 10:24 UTC, Simson475 commented on Simulation/Pathfinding/Solution.cpp
> +#include "Solution.hpp"
+1

2022-03-29 10:24 UTC, Simson475 commented on Simulation/controllers/GreedyStationCBSWaypoint.cpp
> +#include "GreedyStationCBSWaypoint.hpp"
yeet

2022-03-31 06:28 UTC, BjoerklundJacob commented on Simulation/Pathfinding/Action.cpp
> +Action::Action(const Action& a){
altså bare linje 3?

2022-03-31 06:30 UTC, BjoerklundJacob commented on Simulation/Pathfinding/ActionPathAux.cpp
> +#include "ActionPathAux.hpp"
har du et? Det er en aux klasse der binder Action og Path sammen under pathfinding (og med prioritet, så den kan bruges til A*)

2022-03-31 06:31 UTC, BjoerklundJacob commented on Simulation/Pathfinding/ActionPathAux.cpp
> +    return a.priority > b.priority;
ja, der er en test til at sikre at det giver det resultat vi vil have, men det kan godt skrives på en anden måde hvis vi hellere vil have det.

2022-03-31 06:32 UTC, BjoerklundJacob commented on Simulation/Pathfinding/Agent.cpp
> +std::shared_ptr<Vertex> Agent::getGoal(){
ja, men synes getGoal er et bedre navn i forhold til pathfinding, hvor den bruges.

2022-03-31 08:10 UTC, Simson475 approved these changes

2022-03-31 08:10 UTC, merged